### ISSUE TITLE
Unable to activate venv

### ISSUE THREAD

**Issue by shabh2412** [Christo77793/The-Living-Word#1]
I was trying to run the project, but I am unable to activate the virtual environment provided in the repository. The venv folder is missing bin folder and activate file.

**Comment by Christo77793** [comment]
The venv folder was automatically created by PyCharm, and I hadn't noticed the absence of the bin folder. Will fix this, thank you for raising this issue.

**Comment by Christo77793** [comment]
Try this fix, in the venv folder you will find a file called pyvenv.cfg. In that you will find a variable home, update that location to where your python is installed.
